[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stackoverflow_demo"
version = "0.1.0"
description = "A Demo for my stackoverflow question"
dependencies = [
    "my_local_package @ {root:uri}/my_local_package",
]